# 'n' tag is used twice: 'n':'Case=Nom' and 'n':'Mood=Ind|Tense=Pres|Person=1|Number=Sing|Voice=Act' (verbs only)
abbr = {'Y': 'Yes'}
case = {'ab': 'Abe', 'abl': 'Abl', 'ad': 'Ade', 'adt': 'Add', 'all': 'All', 'el': 'Ela', 'es': 'Ess', 'g': 'Gen',
        'ill': 'Ill', 'in': 'Ine', 'kom': 'Com', 'p': 'Par', 'ter': 'Ter', 'tr': 'Tra', 'pl ab': 'Abe',
        'pl abl': 'Abl', 'pl ad': 'Ade', 'pl adt': 'Add', 'pl all': 'All', 'pl el': 'Ela', 'pl es': 'Ess',
        'pl g': 'Gen', 'pl ill': 'Ill', 'pl in': 'Ine', 'pl kom': 'Com', 'pl n': 'Nom', 'pl p': 'Par',
        'pl ter': 'Ter', 'pl tr': 'Tra', 'sg ab': 'Abe', 'sg abl': 'Abl', 'sg ad': 'Ade', 'sg adt': 'Add',
        'sg all': 'All', 'sg el': 'Ela', 'sg es': 'Ess', 'sg g': 'Gen', 'sg ill': 'Ill', 'sg in': 'Ine',
        'sg kom': 'Com', 'sg n': 'Nom', 'sg p': 'Par', 'sg ter': 'Ter', 'sg tr': 'Tra', 'ma': 'Ill', 'maks': 'Tra',
        'mas': 'Ine', 'mast': 'Ela', 'mata': 'Abe', 'n': 'Nom'}
degree = {'A': 'Pos', 'C': 'Cmp', 'U': 'Sup'}
mood = {'b': 'Ind', 'd': 'Ind', 'ge': 'Imp', 'gem': 'Imp', 'gu': 'Imp', 'ks': 'Cnd', 'ksid': 'Cnd', 'ksime': 'Cnd',
        'ksin': 'Cnd',
        'ksite': 'Cnd', 'me': 'Ind', 'n': 'Ind', 'neg ge': 'Imp', 'neg gem': 'Imp', 'neg gu': 'Imp',
        'neg ks': 'Cnd',
        'neg nud': 'Ind', 'neg nuks': 'Cnd', 'neg vat': 'Qot', 'nuks': 'Cnd', 'nuksid': 'Cnd', 'nuksime': 'Cnd',
        'nuksin': 'Cnd', 'nuksite': 'Cnd', 'nuvat': 'Qot', 'o': 'Imp', 's': 'Ind', 'sid': 'Ind',
        'sime': 'Ind', 'sin': 'Ind', 'site': 'Ind', 'ta': 'Ind', 'tagu': 'Imp', 'taks': 'Cnd', 'takse': 'Ind',
        'tavat': 'Qot',
        'te': 'Ind', 'ti': 'Ind', 'tuks': 'Cnd', 'tuvat': 'Qot', 'vad': 'Ind', 'vat': 'Qot'}
mood_chain = {'imper': 'Imp', 'indic': 'Ind', 'condit': 'Cnd', 'quotat': 'Qot'}
negative = {'neg ge': 'Neg', 'neg gem': 'Neg', 'neg gu': 'Neg', 'neg ks': 'Neg', 'neg nud': 'Neg',
            'neg nuks': 'Neg', 'neg o': 'Neg', 'neg vat': 'Neg', 'ta': 'Neg', 'neg': 'Neg'}
number = {'pl ab': 'Plur', 'pl abl': 'Plur', 'pl ad': 'Plur', 'pl adt': 'Plur', 'pl all': 'Plur',
          'pl el': 'Plur', 'pl es': 'Plur', 'pl g': 'Plur', 'pl ill': 'Plur', 'pl in': 'Plur', 'pl kom': 'Plur',
          'pl n': 'Plur', 'pl p': 'Plur', 'pl ter': 'Plur', 'pl tr': 'Plur', 'sg ab': 'Sing', 'sg abl': 'Sing',
          'sg ad': 'Sing', 'sg adt': 'Sing', 'sg all': 'Sing', 'sg el': 'Sing',
          'sg es': 'Sing', 'sg g': 'Sing', 'sg ill': 'Sing', 'sg in': 'Sing', 'sg kom': 'Sing', 'sg n': 'Sing',
          'sg p': 'Sing', 'sg ter': 'Sing', 'sg tr': 'Sing', 'b': 'Sing', 'd': 'Sing', 'ge': 'Plur', 'gem': 'Plur',
          'ksime': 'Plur', 'ksin': 'Sing', 'ksite': 'Plur', 'me': 'Plur', 'n': 'Sing', 'neg ge': 'Plur',
          'neg gem': 'Plur', 'nuksime': 'Plur', 'nuksin': 'Sing', 'nuksite': 'Plur', 'o': 'Sing', 's': 'Sing',
          'sime': 'Plur', 'sin': 'Sing', 'site': 'Plur', 'te': 'Plur', 'vad': 'Plur'}
numtype = {'N': 'Card', 'O': 'Ord'}
person = {'b': '3', 'd': '2', 'ge': '2', 'gem': '1', 'gu': '3', 'ksime': '1', 'ksin': '1', 'ksite': '2', 'me': '1',
          'n': '1', 'neg ge': '2', 'neg gem': '1', 'nuksin': '1', 'nuksite': '2', 's': '3', 'sime': '1', 'sin': '1',
          'site': '2', 'te': '2', 'vad': '3'}
person_pron = {'mina': '1', 'sina': '2', 'tema': '3'}
prontype = {'eimiski': 'Ind', 'ei-tea-mitmes': 'Int,Rel', 'esimene': 'Dem', 'iga': 'Tot', 'igasugune': 'Ind',
            'igaüks': 'Dem', 'iga-sugune': 'Ind', 'ise': 'Prs', 'iseenese': 'Prs', 'keegi': 'Ind', 'kes': 'Int,Rel',
            'kõik': 'Tot', 'kolmas': 'Dem', 'kumb': 'Rel', 'ma': 'Prs', 'meiesugune': 'Dem', 'mi-mina': 'Prs',
            'milline': 'Rel', 'mina': 'Prs', 'mingi': 'Ind', 'mingisugune': 'Ind', 'minusugune': 'Dem',
            'minu-mina': 'Prs', 'mis': 'Int,Rel', 'missugune': 'Int,Rel', 'miski': 'Ind', 'mitmesugune': 'Ind',
            'mitmes': 'Int,Rel', 'mitu': 'Ind', 'mõlema': 'Tot', 'mõni': 'Ind', 'muist': 'Ind', 'muu': 'Ind',
            'neljas': 'Dem', 'nihuke': 'Dem', 'niisugune': 'Dem', 'oma': 'Prs', 'omaenese': 'Prs',
            'omasugune': 'Dem', 'palju': 'Ind', 'säärane': 'Dem', 'säherdune': 'Dem', 'sama': 'Dem',
            'samasugune': 'Dem', 'see': 'Dem', 'seesama': 'Dem', 'seesugune': 'Dem', 'see-ja-see': 'Dem',
            'see-sama': 'Dem', 'selline': 'Dem', 'sihuke': 'Dem', 'sina': 'Prs', 'siuke': 'Dem', 'taoline': 'Dem',
            'teiesugune': 'Dem', 'teine': 'Dem', 'teistsugune': 'Dem', 'tema': 'Prs', 'temasugune': 'Dem',
            'too': 'Dem', 'toosama': 'Dem', 'üks': 'Dem', 'üksteise': 'Dem', 'üksteist': 'Ind', 'ükski': 'Ind'}
reflex = {'ise': 'Yes', 'oma': 'Yes', 'iseenese': 'Yes', 'üksteise': 'Yes', 'teineteise': 'Yes', 'omaenese': 'Yes'}
tense = {'b': 'Pres', 'd': 'Pres', 'ge': 'Pres', 'gem': 'Pres', 'gu': 'Pres', 'ks': 'Pres', 'ksid': 'Pres',
         'ksime': 'Pres', 'ksin': 'Pres', 'ksite': 'Pres', 'me': 'Pres', 'n': 'Pres', 'neg ge': 'Pres',
         'neg gem': 'Pres', 'neg gu': 'Pres', 'neg ks': 'Pres', 'neg nud': 'Past', 'neg nuks': 'Past',
         'neg o': 'Pres', 'neg vat': 'Pres', 'nud': 'Past', 'nuks': 'Past', 'nuksid': 'Past', 'nuksime': 'Past',
         'nuksin': 'Past', 'nuksite': 'Past', 'nuvat': 'Past', 'o': 'Pres', 's': 'Past', 'sid': 'Past',
         'sime': 'Past', 'sin': 'Past', 'site': 'Past', 'ta': 'Pres', 'tagu': 'Pres', 'taks': 'Pres',
         'takse': 'Pres', 'tav': 'Pres', 'tavat': 'Pres', 'te': 'Pres', 'ti': 'Past', 'tud': 'Past', 'tuks': 'Past',
         'tuvat': 'Past', 'v': 'Pres', 'vad': 'Pres', 'vat': 'Pres'}
tense_chain = {'present': 'Pres', 'imperfect': 'Imp', 'perfect': 'Past', 'pluperfect': 'Past', 'past': 'Past'}
verbform = {'da': 'Inf', 'des': 'Ger', 'ma': 'Sup', 'maks': 'Sup', 'mas': 'Sup', 'mast': 'Sup', 'mata': 'Sup',
            'nud': 'Part', 'tama': 'Sup', 'tav': 'Part', 'tud': 'Part', 'v': 'Part', 'd': 'Fin', 'ge': 'Fin',
            'gem': 'Fin', 'gu': 'Fin', 'ks': 'Fin', 'ksid': 'Fin', 'ksime': 'Fin', 'ksin': 'Fin',
            'ksite': 'Fin', 'me': 'Fin', 'n': 'Fin', 'neg ge': 'Fin', 'neg gem': 'Fin', 'neg gu': 'Fin',
            'neg ks': 'Fin',
            'neg nud': 'Fin', 'neg nuks': 'Fin', 'neg vat': 'Fin', 'nuks': 'Fin', 'nuksid': 'Fin', 'nuksime': 'Fin',
            'nuksin': 'Fin', 'nuksite': 'Fin', 'nuvat': 'Fin', 'o': 'Fin', 's': 'Fin', 'sid': 'Fin',
            'sime': 'Fin', 'sin': 'Fin', 'site': 'Fin', 'ta': 'Fin', 'tagu': 'Fin', 'taks': 'Fin', 'takse': 'Fin',
            'tavat': 'Fin',
            'te': 'Fin', 'ti': 'Fin', 'tuks': 'Fin', 'tuvat': 'Fin', 'vad': 'Fin', 'vat': 'Fin'}
voice = {'b': 'Act', 'd': 'Act', 'ge': 'Act', 'gem': 'Act', 'gu': 'Act', 'ks': 'Act', 'ksid': 'Act', 'ksime': 'Act',
         'ksin': 'Act', 'ksite': 'Act', 'ma': 'Act', 'maks': 'Act', 'mas': 'Act', 'mast': 'Act', 'mata': 'Act',
         'me': 'Act', 'n': 'Act', 'neg ge': 'Act', 'neg gem': 'Act', 'neg ks': 'Act', 'neg nud': 'Act',
         'neg nuks': 'Act', 'neg o': 'Act', 'neg vat': 'Act', 'nud': 'Act', 'nuks': 'Act', 'nuksid': 'Act',
         'nuksime': 'Act', 'nuksin': 'Act', 'nuksite': 'Act', 'nuvat': 'Act', 'o': 'Act', 's': 'Act', 'sid': 'Act',
         'sime': 'Act', 'sin': 'Act', 'site': 'Act', 'ta': 'Pass', 'tagu': 'Pass', 'taks': 'Pass', 'takse': 'Pass',
         'tama': 'Pass', 'tav': 'Pass', 'tavat': 'Pass', 'te': 'Act', 'ti': 'Pass', 'tud': 'Pass', 'tuks': 'Pass',
         'tuvat': 'Pass', 'v': 'Act', 'vad': 'Act', 'vat': 'Act'}
voice_chain = {'personal': 'Act', 'impersonal': 'Pass'}
adptype = {'abil': 'Post', 'aega': 'Post', 'aegu': 'Post', 'ajal': 'Post', 'ajel': 'Post', 'algul': 'Post',
           'algult': 'Post', 'all': 'Post', 'allapoole': 'Prep', 'allpool': 'Prep', 'alt': 'Post',
           'altpoolt': 'Prep', 'arust': 'Post', 'arvel': 'Post', 'arvele': 'Post', 'arvelt': 'Post',
           'asemel': 'Post', 'asemele': 'Post', 'edasi': 'Post', 'eel': 'Post', 'eeli': 'Post', 'ees': 'Post',
           'eest': 'Post', 'enne': 'Prep', 'ette': 'Post', 'ettepoole': 'Prep', 'eespool': 'Prep',
           'eestpoolt': 'Prep', 'haaval': 'Post', 'hakul': 'Post', 'heaks': 'Post', 'hommikupoole': 'Prep',
           'hulgas': 'Post', 'hulgast': 'Post', 'hulka': 'Post', 'ilma': 'Prep', 'jaoks': 'Post', 'jooksul': 'Post',
           'jõul': 'Post', 'juurde': 'Post', 'juures': 'Post', 'juurest': 'Post', 'järel': 'Post', 'järele': 'Post',
           'järelt': 'Post', 'järgi': 'Post', 'kaasas': 'Post', 'kaela': 'Post', 'kaelas': 'Post',
           'kaelast': 'Post', 'kallal': 'Post', 'kallale': 'Post', 'kallalt': 'Post', 'kandis': 'Post',
           'kannul': 'Post', 'kannule': 'Post', 'kannult': 'Post', 'kanti': 'Post', 'kaudu': 'Post',
           'kaugusel': 'Post', 'kaupa': 'Post', 'keset': 'Prep', 'kesk': 'Prep', 'keskel': 'Post',
           'keskele': 'Post', 'keskelt': 'Post', 'kestel': 'Post', 'kilda': 'Post', 'killas': 'Post',
           'killast': 'Post', 'kimpu': 'Post', 'kiuste': 'Post', 'kohal': 'Post', 'kohale': 'Post',
           'kohalt': 'Post', 'kohaselt': 'post', 'kohta': 'Post', 'kombel': 'Post', 'korral': 'Post',
           'kõrval': 'Post', 'kõrvale': 'Post', 'kõrvalt': 'Post', 'kujul': 'Post', 'kukil': 'Post',
           'kukile': 'Post', 'kukilt': 'Post', 'kulul': 'Post', 'kuni': 'Prep', 'käes': 'Post', 'käest': 'Post',
           'käigus': 'Post', 'kätte': 'Post', 'külge': 'Post', 'küljes': 'Post', 'küljest': 'Post', 'küüsi': 'Post',
           'küüsis': 'Post', 'küüsist': 'Post', 'ligidal': 'Post', 'ligidale': 'Post', 'ligidalt': 'Post',
           'lähedal': 'Post', 'lähedale': 'Post', 'lähedalt': 'Post', 'lähistel': 'Post', 'lähistele': 'Post',
           'lähistelt': 'Post', 'man': 'Post', 'mant': 'Post', 'manu': 'Post', 'meelest': 'Post', 'moel': 'Post',
           'moodi': 'Post', 'mõjul': 'Post', 'najal': 'Post', 'najale': 'Post', 'najalt': 'Post', 'nimel': 'Post',
           'nõjal': 'Post', 'näol': 'Post', 'näpuvahele': 'Post', 'osas': 'Post', 'otsas': 'Post', 'otsast': 'Post',
           'õlul': 'Post', 'õlule': 'Post', 'õlult': 'Post', 'paiku': 'Post', 'peal': 'Post', 'pealepoole': 'Prep',
           'pealpool': 'Prep', 'pealtpoolt': 'Prep', 'peast': 'Post', 'pidi': 'Post', 'pihta': 'Post',
           'piires': 'Post', 'piki': 'Prep', 'pikku': 'Post', 'pool': 'Post', 'poole': 'Post', 'poolest': 'Post',
           'poolt': 'Post', 'põhjal': 'Post', 'puhul': 'Post', 'pähe': 'Post', 'päralt': 'Post', 'raames': 'Post',
           'ringi': 'Post', 'ringis': 'Post', 'saadik': 'Post', 'saatel': 'Post', 'saati': 'Post',
           'sealpool': 'Prep', 'sealtpoolt': 'Prep', 'seas': 'Post', 'seast': 'Post', 'sekka': 'Post',
           'sees': 'Post', 'seespool': 'Prep', 'seest': 'Post', 'seestpoolt': 'Prep', 'seltsi': 'Post',
           'seltsis': 'Post', 'seltsist': 'Post', 'siiapoole': 'Prep', 'siinpool': 'Prep', 'siitpoolt': 'Prep',
           'sinnapoole': 'Prep', 'sisse': 'Post', 'sissepoole': 'Prep', 'suhtes': 'Post', 'sunnil': 'Post',
           'suunas': 'Post', 'suunast': 'Post', 'suunda': 'Post', 'taga': 'Post', 'tagant': 'Post',
           'tagantpoolt': 'Prep', 'tagapool': 'Prep', 'tagasi': 'Post', 'taha': 'Post', 'tahapoole': 'Prep',
           'takka': 'Post', 'tarvis': 'Post', 'teel': 'Post', 'teispool': 'Prep', 'teispoole': 'Prep',
           'teispoolt': 'Prep', 'toel': 'Post', 'tõttu': 'Post', 'tõukel': 'Post', 'tänu': 'Prep', 'vahel': 'Post',
           'vahele': 'Post', 'vahelt': 'Post', 'vahet': 'post', 'varal': 'Post', 'varale': 'Post', 'varju': 'Post',
           'varjus': 'Post', 'varjust': 'Post', 'varul': 'Post', 'vastas': 'Post', 'vastast': 'Post',
           'vastavalt': 'Prep', 'veerde': 'Post', 'veeres': 'Post', 'veerest': 'Post', 'viisi': 'Post',
           'viisil': 'Post', 'võidu': 'Post', 'võrra': 'Post', 'väel': 'Post', 'väele': 'Post',
           'väljapoole': 'Prep', 'väljaspool': 'Prep', 'väljastpoolt': 'Prep', 'vältel': 'Post', 'äärde': 'Post',
           'ääres': 'Post', 'äärest': 'Post', 'ühelepoole': 'Prep', 'ühelpool': 'Prep', 'üheltpoolt': 'Prep',
           'ülalpool': 'Prep', 'ülaltpoolt': 'Prep', 'ülespoole': 'Prep', 'ülevalpool': 'Prep',
           'ülevaltpoolt': 'Prep'}
uposdict = {'A': 'ADJ', 'C': 'ADJ', 'D': 'ADV', 'G': 'ADJ', 'H': 'PROPN', 'I': 'INTJ', 'K': 'ADP', 'N': 'NUM',
            'O': 'NUM', 'P': 'PRON', 'S': 'NOUN', 'U': 'ADJ', 'V': 'VERB', 'Z': 'PUNCT'}
conjdict = {'aga': 'CONJ', 'ega': 'CONJ', 'ehk': 'CONJ', 'ent': 'CONJ', 'ja': 'CONJ', 'kuid': 'CONJ',
            'ning': 'CONJ', 'või': 'CONJ', 'vaid': 'CONJ', 'ehkki': 'SCONJ', 'et': 'SCONJ', 'justkui': 'SCONJ',
            'kui': 'SCONJ', 'kuigi': 'SCONJ', 'kuna': 'SCONJ', 'kuni': 'SCONJ', 'nagu': 'SCONJ', 'olgugi': 'SCONJ',
            'otsekui': 'SCONJ', 'sest': 'SCONJ'}
xposdict = {'A': 'A', 'C': 'A', 'D': 'D', 'G': 'G', 'H': 'S', 'I': 'I', 'J': 'J', 'K': 'K', 'N': 'N', 'O': 'N',
            'P': 'P', 'S': 'S', 'U': 'A', 'V': 'V', 'X': 'D', 'Y': 'Y', 'Z': 'Z'}